/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DelegatedAuthorityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDelegate"
      | "canExecute"
      | "deactivateTarget"
      | "delegates"
      | "grantPermission"
      | "isDelegate"
      | "isPermissionGranted"
      | "kaizenExecutor"
      | "ownerOf"
      | "registerTarget"
      | "removeDelegate"
      | "revokePermission"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DelegateAdded"
      | "DelegateRemoved"
      | "PermissionGranted"
      | "PermissionRevoked"
      | "TargetDeactivated"
      | "TargetRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addDelegate",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canExecute",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateTarget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "delegates",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantPermission",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDelegate",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPermissionGranted",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "kaizenExecutor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerTarget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDelegate",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokePermission",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delegates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isDelegate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPermissionGranted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kaizenExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokePermission",
    data: BytesLike
  ): Result;
}

export namespace DelegateAddedEvent {
  export type InputTuple = [target: AddressLike, delegate: AddressLike];
  export type OutputTuple = [target: string, delegate: string];
  export interface OutputObject {
    target: string;
    delegate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DelegateRemovedEvent {
  export type InputTuple = [target: AddressLike, delegate: AddressLike];
  export type OutputTuple = [target: string, delegate: string];
  export interface OutputObject {
    target: string;
    delegate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PermissionGrantedEvent {
  export type InputTuple = [target: AddressLike, selector: BytesLike];
  export type OutputTuple = [target: string, selector: string];
  export interface OutputObject {
    target: string;
    selector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PermissionRevokedEvent {
  export type InputTuple = [target: AddressLike, selector: BytesLike];
  export type OutputTuple = [target: string, selector: string];
  export interface OutputObject {
    target: string;
    selector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetDeactivatedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetRegisteredEvent {
  export type InputTuple = [target: AddressLike, owner: AddressLike];
  export type OutputTuple = [target: string, owner: string];
  export interface OutputObject {
    target: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DelegatedAuthority extends BaseContract {
  connect(runner?: ContractRunner | null): DelegatedAuthority;
  waitForDeployment(): Promise<this>;

  interface: DelegatedAuthorityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDelegate: TypedContractMethod<
    [target: AddressLike, delegate: AddressLike],
    [void],
    "nonpayable"
  >;

  canExecute: TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [boolean],
    "view"
  >;

  deactivateTarget: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  delegates: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  grantPermission: TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [void],
    "nonpayable"
  >;

  isDelegate: TypedContractMethod<
    [target: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;

  isPermissionGranted: TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [boolean],
    "view"
  >;

  kaizenExecutor: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[target: AddressLike], [string], "view">;

  registerTarget: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  removeDelegate: TypedContractMethod<
    [target: AddressLike, delegate: AddressLike],
    [void],
    "nonpayable"
  >;

  revokePermission: TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDelegate"
  ): TypedContractMethod<
    [target: AddressLike, delegate: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateTarget"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "delegates"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantPermission"
  ): TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDelegate"
  ): TypedContractMethod<
    [target: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPermissionGranted"
  ): TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "kaizenExecutor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[target: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerTarget"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeDelegate"
  ): TypedContractMethod<
    [target: AddressLike, delegate: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokePermission"
  ): TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DelegateAdded"
  ): TypedContractEvent<
    DelegateAddedEvent.InputTuple,
    DelegateAddedEvent.OutputTuple,
    DelegateAddedEvent.OutputObject
  >;
  getEvent(
    key: "DelegateRemoved"
  ): TypedContractEvent<
    DelegateRemovedEvent.InputTuple,
    DelegateRemovedEvent.OutputTuple,
    DelegateRemovedEvent.OutputObject
  >;
  getEvent(
    key: "PermissionGranted"
  ): TypedContractEvent<
    PermissionGrantedEvent.InputTuple,
    PermissionGrantedEvent.OutputTuple,
    PermissionGrantedEvent.OutputObject
  >;
  getEvent(
    key: "PermissionRevoked"
  ): TypedContractEvent<
    PermissionRevokedEvent.InputTuple,
    PermissionRevokedEvent.OutputTuple,
    PermissionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TargetDeactivated"
  ): TypedContractEvent<
    TargetDeactivatedEvent.InputTuple,
    TargetDeactivatedEvent.OutputTuple,
    TargetDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "TargetRegistered"
  ): TypedContractEvent<
    TargetRegisteredEvent.InputTuple,
    TargetRegisteredEvent.OutputTuple,
    TargetRegisteredEvent.OutputObject
  >;

  filters: {
    "DelegateAdded(address,address)": TypedContractEvent<
      DelegateAddedEvent.InputTuple,
      DelegateAddedEvent.OutputTuple,
      DelegateAddedEvent.OutputObject
    >;
    DelegateAdded: TypedContractEvent<
      DelegateAddedEvent.InputTuple,
      DelegateAddedEvent.OutputTuple,
      DelegateAddedEvent.OutputObject
    >;

    "DelegateRemoved(address,address)": TypedContractEvent<
      DelegateRemovedEvent.InputTuple,
      DelegateRemovedEvent.OutputTuple,
      DelegateRemovedEvent.OutputObject
    >;
    DelegateRemoved: TypedContractEvent<
      DelegateRemovedEvent.InputTuple,
      DelegateRemovedEvent.OutputTuple,
      DelegateRemovedEvent.OutputObject
    >;

    "PermissionGranted(address,bytes4)": TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;
    PermissionGranted: TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;

    "PermissionRevoked(address,bytes4)": TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;
    PermissionRevoked: TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;

    "TargetDeactivated(address)": TypedContractEvent<
      TargetDeactivatedEvent.InputTuple,
      TargetDeactivatedEvent.OutputTuple,
      TargetDeactivatedEvent.OutputObject
    >;
    TargetDeactivated: TypedContractEvent<
      TargetDeactivatedEvent.InputTuple,
      TargetDeactivatedEvent.OutputTuple,
      TargetDeactivatedEvent.OutputObject
    >;

    "TargetRegistered(address,address)": TypedContractEvent<
      TargetRegisteredEvent.InputTuple,
      TargetRegisteredEvent.OutputTuple,
      TargetRegisteredEvent.OutputObject
    >;
    TargetRegistered: TypedContractEvent<
      TargetRegisteredEvent.InputTuple,
      TargetRegisteredEvent.OutputTuple,
      TargetRegisteredEvent.OutputObject
    >;
  };
}
