/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface KillSwitchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COOLDOWN"
      | "authority"
      | "kaizenExecutor"
      | "lastTriggered"
      | "resumeProtocol"
      | "triggerKillSwitch"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "KillSwitchTriggered" | "ProtocolResumed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "COOLDOWN", values?: undefined): string;
  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "kaizenExecutor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastTriggered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resumeProtocol",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerKillSwitch",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "COOLDOWN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kaizenExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastTriggered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerKillSwitch",
    data: BytesLike
  ): Result;
}

export namespace KillSwitchTriggeredEvent {
  export type InputTuple = [
    target: AddressLike,
    executor: AddressLike,
    selector: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    target: string,
    executor: string,
    selector: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    target: string;
    executor: string;
    selector: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolResumedEvent {
  export type InputTuple = [target: AddressLike, owner: AddressLike];
  export type OutputTuple = [target: string, owner: string];
  export interface OutputObject {
    target: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KillSwitch extends BaseContract {
  connect(runner?: ContractRunner | null): KillSwitch;
  waitForDeployment(): Promise<this>;

  interface: KillSwitchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  authority: TypedContractMethod<[], [string], "view">;

  kaizenExecutor: TypedContractMethod<[], [string], "view">;

  lastTriggered: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  resumeProtocol: TypedContractMethod<
    [target: AddressLike, resumeCallData: BytesLike],
    [void],
    "nonpayable"
  >;

  triggerKillSwitch: TypedContractMethod<
    [target: AddressLike, pauseCallData: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "kaizenExecutor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastTriggered"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "resumeProtocol"
  ): TypedContractMethod<
    [target: AddressLike, resumeCallData: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "triggerKillSwitch"
  ): TypedContractMethod<
    [target: AddressLike, pauseCallData: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "KillSwitchTriggered"
  ): TypedContractEvent<
    KillSwitchTriggeredEvent.InputTuple,
    KillSwitchTriggeredEvent.OutputTuple,
    KillSwitchTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolResumed"
  ): TypedContractEvent<
    ProtocolResumedEvent.InputTuple,
    ProtocolResumedEvent.OutputTuple,
    ProtocolResumedEvent.OutputObject
  >;

  filters: {
    "KillSwitchTriggered(address,address,bytes4,uint256)": TypedContractEvent<
      KillSwitchTriggeredEvent.InputTuple,
      KillSwitchTriggeredEvent.OutputTuple,
      KillSwitchTriggeredEvent.OutputObject
    >;
    KillSwitchTriggered: TypedContractEvent<
      KillSwitchTriggeredEvent.InputTuple,
      KillSwitchTriggeredEvent.OutputTuple,
      KillSwitchTriggeredEvent.OutputObject
    >;

    "ProtocolResumed(address,address)": TypedContractEvent<
      ProtocolResumedEvent.InputTuple,
      ProtocolResumedEvent.OutputTuple,
      ProtocolResumedEvent.OutputObject
    >;
    ProtocolResumed: TypedContractEvent<
      ProtocolResumedEvent.InputTuple,
      ProtocolResumedEvent.OutputTuple,
      ProtocolResumedEvent.OutputObject
    >;
  };
}
