/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AntonTimeLockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_LOCK_DURATION"
      | "MAX_LOCK_DURATION"
      | "authority"
      | "isLocked"
      | "kaizenExecutor"
      | "lockDuration"
      | "lockedUntil"
      | "manualUnlock"
      | "setLockDuration"
      | "triggerTimelock"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ManualUnlock"
      | "TimelockDurationUpdated"
      | "TimelockTriggered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_LOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isLocked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "kaizenExecutor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockDuration",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedUntil",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manualUnlock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLockDuration",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerTimelock",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_LOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isLocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kaizenExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockedUntil",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manualUnlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerTimelock",
    data: BytesLike
  ): Result;
}

export namespace ManualUnlockEvent {
  export type InputTuple = [target: AddressLike, owner: AddressLike];
  export type OutputTuple = [target: string, owner: string];
  export interface OutputObject {
    target: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockDurationUpdatedEvent {
  export type InputTuple = [target: AddressLike, duration: BigNumberish];
  export type OutputTuple = [target: string, duration: bigint];
  export interface OutputObject {
    target: string;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockTriggeredEvent {
  export type InputTuple = [
    target: AddressLike,
    executor: AddressLike,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    target: string,
    executor: string,
    unlockTime: bigint
  ];
  export interface OutputObject {
    target: string;
    executor: string;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AntonTimeLock extends BaseContract {
  connect(runner?: ContractRunner | null): AntonTimeLock;
  waitForDeployment(): Promise<this>;

  interface: AntonTimeLockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_LOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_LOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  authority: TypedContractMethod<[], [string], "view">;

  isLocked: TypedContractMethod<[target: AddressLike], [boolean], "view">;

  kaizenExecutor: TypedContractMethod<[], [string], "view">;

  lockDuration: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  lockedUntil: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  manualUnlock: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  setLockDuration: TypedContractMethod<
    [target: AddressLike, duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  triggerTimelock: TypedContractMethod<
    [target: AddressLike, callData: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_LOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isLocked"
  ): TypedContractMethod<[target: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "kaizenExecutor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lockDuration"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockedUntil"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "manualUnlock"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLockDuration"
  ): TypedContractMethod<
    [target: AddressLike, duration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "triggerTimelock"
  ): TypedContractMethod<
    [target: AddressLike, callData: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ManualUnlock"
  ): TypedContractEvent<
    ManualUnlockEvent.InputTuple,
    ManualUnlockEvent.OutputTuple,
    ManualUnlockEvent.OutputObject
  >;
  getEvent(
    key: "TimelockDurationUpdated"
  ): TypedContractEvent<
    TimelockDurationUpdatedEvent.InputTuple,
    TimelockDurationUpdatedEvent.OutputTuple,
    TimelockDurationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockTriggered"
  ): TypedContractEvent<
    TimelockTriggeredEvent.InputTuple,
    TimelockTriggeredEvent.OutputTuple,
    TimelockTriggeredEvent.OutputObject
  >;

  filters: {
    "ManualUnlock(address,address)": TypedContractEvent<
      ManualUnlockEvent.InputTuple,
      ManualUnlockEvent.OutputTuple,
      ManualUnlockEvent.OutputObject
    >;
    ManualUnlock: TypedContractEvent<
      ManualUnlockEvent.InputTuple,
      ManualUnlockEvent.OutputTuple,
      ManualUnlockEvent.OutputObject
    >;

    "TimelockDurationUpdated(address,uint256)": TypedContractEvent<
      TimelockDurationUpdatedEvent.InputTuple,
      TimelockDurationUpdatedEvent.OutputTuple,
      TimelockDurationUpdatedEvent.OutputObject
    >;
    TimelockDurationUpdated: TypedContractEvent<
      TimelockDurationUpdatedEvent.InputTuple,
      TimelockDurationUpdatedEvent.OutputTuple,
      TimelockDurationUpdatedEvent.OutputObject
    >;

    "TimelockTriggered(address,address,uint256)": TypedContractEvent<
      TimelockTriggeredEvent.InputTuple,
      TimelockTriggeredEvent.OutputTuple,
      TimelockTriggeredEvent.OutputObject
    >;
    TimelockTriggered: TypedContractEvent<
      TimelockTriggeredEvent.InputTuple,
      TimelockTriggeredEvent.OutputTuple,
      TimelockTriggeredEvent.OutputObject
    >;
  };
}
