/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDelegatedAuthority__factory } from "./IDelegatedAuthority__factory";
export { KillSwitch__factory } from "./KillSwitch__factory";
