/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AntonTimeLock } from "./AntonTimeLock";
export type { IDelegatedAuthority } from "./IDelegatedAuthority";
