/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDelegatedAuthority,
  IDelegatedAuthorityInterface,
} from "../../KillSwitch/IDelegatedAuthority";

const _abi = [
  {
    type: "function",
    name: "canExecute",
    inputs: [
      {
        name: "target",
        type: "address",
        internalType: "address",
      },
      {
        name: "selector",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ownerOf",
    inputs: [
      {
        name: "target",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IDelegatedAuthority__factory {
  static readonly abi = _abi;
  static createInterface(): IDelegatedAuthorityInterface {
    return new Interface(_abi) as IDelegatedAuthorityInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDelegatedAuthority {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDelegatedAuthority;
  }
}
