/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDelegatedAuthority } from "./IDelegatedAuthority";
export type { KillSwitch } from "./KillSwitch";
