/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AntonTimeLock__factory } from "./AntonTimeLock__factory";
export { IDelegatedAuthority__factory } from "./IDelegatedAuthority__factory";
