/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as antonTimlelock from "./AntonTimlelock";
export type { antonTimlelock };
import type * as killSwitch from "./KillSwitch";
export type { killSwitch };
export type { DelegatedAuthority } from "./DelegatedAuthority";
export * as factories from "./factories";
export type { AntonTimeLock } from "./AntonTimlelock/AntonTimeLock";
export { AntonTimeLock__factory } from "./factories/AntonTimlelock/AntonTimeLock__factory";
export type { IDelegatedAuthority } from "./AntonTimlelock/IDelegatedAuthority";
export { IDelegatedAuthority__factory } from "./factories/AntonTimlelock/IDelegatedAuthority__factory";
export { DelegatedAuthority__factory } from "./factories/DelegatedAuthority__factory";
export type { KillSwitch } from "./KillSwitch/KillSwitch";
export { KillSwitch__factory } from "./factories/KillSwitch/KillSwitch__factory";
